#!usr/bin/env bash
# worldwide web
#!/usr/bin/env bash
# Configuring domain zone to www for my server
function check_args() {
	if [ $# -lt 1 ]; then
		echo "Usage: <Argument 1> <Argument 2>"
		return 1
	fi
}

dig_domain () {
	ans_line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $ans_line" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3""}'
}

if  [ "$#" == 1 ]; then
	dig_domain "$1" "www"
	dig_domain "$1" "lb-01"
	dig_domain "$1" "web-01"
	dig_domain "$1" "web-02"
elif [ "$#" == 2 ]; then
	dig_domain "$1" "$2"
else
	echo "Usage: <arg1> <arg2>"
fi
